using UnityEngine;
using UnityEngine.UI;
using System.Diagnostics;
using System.Net.Http;
using System.Collections.Generic;

// 'Run ollama serve' in command prompt before starting the Unity scene
// 'ollama pull mistral' if ollama model not downloaded yet

namespace Samples.Whisper
{
    public class Whisper : MonoBehaviour
    {
        [SerializeField] private Button recordButton;
        [SerializeField] private Image progressBar;
        [SerializeField] private Text message;
        [SerializeField] private Dropdown dropdown;

        [SerializeField] private AudioSource audioSource;

        private readonly string piperPath = "C:/Users/anita/Downloads/piper_windows_amd64/piper/piper.exe";
        private readonly string piperModel = "C:/Users/anita/Downloads/piper_windows_amd64/piper/models/en_US-joe-medium.onnx";
        private string piperOutput; //Audio file generated by piper text-to-speech model, which will be played in the audio source after receiving response from Ollama
        
        private readonly string fileName = "output.wav"; //Temporary file to save user recording before sending to whisper for transcription
        private readonly int duration = 5; //Recording duration in seconds
        
        // Ollama settings
        private readonly string ollamaUrl = "http://localhost:11434/api/generate";
        private readonly string ollamaModel = "mistral";

        ////////TODO: take system prompt into other script//////////////
        private readonly string ollamaSystemPrompt = "You are a helpful teacher. Answer questions as if you are teaching a student. Keep responses clear and educational.";
        ////////////////////////////////////////////////////////////

        private AudioClip clip;
        private bool isRecording;
        private float time;
        
        private static HttpClient httpClient = new HttpClient();

        private void Start()
        {
            piperOutput = Application.persistentDataPath + "/response.wav";

            #if UNITY_WEBGL && !UNITY_EDITOR
            dropdown.options.Add(new Dropdown.OptionData("Microphone not supported on WebGL"));
            #else
            foreach (var device in Microphone.devices)
            {
                dropdown.options.Add(new Dropdown.OptionData(device));
            }
            recordButton.onClick.AddListener(StartRecording);
            dropdown.onValueChanged.AddListener(ChangeMicrophone);
            
            var index = PlayerPrefs.GetInt("user-mic-device-index");
            dropdown.SetValueWithoutNotify(index);
            #endif
        }

        private void ChangeMicrophone(int index)
        {
            PlayerPrefs.SetInt("user-mic-device-index", index);
        }
        
        private void StartRecording()
        {
            isRecording = true;
            recordButton.enabled = false;

            var index = PlayerPrefs.GetInt("user-mic-device-index");
            
            #if !UNITY_WEBGL
            clip = Microphone.Start(dropdown.options[index].text, false, duration, 44100);
            #endif
        }

////////////////////

        private async void EndRecording()
    {
        message.text = "Transcribing...";

    #if !UNITY_WEBGL
    Microphone.End(null);
    #endif

    // wait a frame so Unity finalizes the clip
    await System.Threading.Tasks.Task.Delay(100);

/////////// 

    UnityEngine.Debug.Log("Clip samples: " + clip.samples);

    string audioPath = Application.persistentDataPath + "/" + fileName;

    byte[] data = SaveWav.Save(fileName, clip);
    System.IO.File.WriteAllBytes(audioPath, data);

    UnityEngine.Debug.Log("Audio file: " + audioPath);

///////////

        string whisperPath = "C:/Users/anita/Downloads/whisper-bin-x64/Release/whisper-cli.exe";
        string modelPath = "C:/Users/anita/Downloads/whisper-bin-x64/Release/models/ggml-base.en.bin";

        string result = await System.Threading.Tasks.Task.Run(() =>
        {
            using (Process process = new Process())
            {
                process.StartInfo.FileName = whisperPath;
                process.StartInfo.Arguments = "-m \"" + modelPath + "\" -f \"" + audioPath + "\"";
                process.StartInfo.RedirectStandardOutput = true;
                process.StartInfo.UseShellExecute = false;
                process.StartInfo.CreateNoWindow = true;

                process.Start();

                string output = process.StandardOutput.ReadToEnd();
                process.WaitForExit();

                process.Close();   // VERY IMPORTANT because it frees up the file lock on the audio file so it can be deleted in the next run
                return output;
            }
        });

        progressBar.fillAmount = 0;
        message.text = result;
        
        //// Query Ollama with the transcribed text. Maybe delete if unecessary to show in UI
        string ollamaResponse = await QueryOllama(result);

        message.text = $"You said:{result}\n---\nTeacher says:{ollamaResponse}";
        ////

        // Generate speech
        await RunPiper(ollamaResponse);

        // Play audio
        StartCoroutine(PlayGeneratedAudio());
        
        recordButton.enabled = true;
    }

/////////////////////////////

        private async System.Threading.Tasks.Task<string> QueryOllama(string transcribedText)
    {
        try
        {
            message.text = "Processing with AI model...";
            
            var requestData = new Dictionary<string, object>
            {
                { "model", ollamaModel },
                { "prompt", transcribedText },
                { "system", ollamaSystemPrompt },
                { "stream", false }
            };

            string json = JsonUtility.ToJson(new OllamaRequest 
            { 
                model = ollamaModel,
                prompt = transcribedText,
                stream = false
            });

            var content = new StringContent(json, System.Text.Encoding.UTF8, "application/json");
            httpClient.Timeout = System.TimeSpan.FromSeconds(120);

            HttpResponseMessage response = await httpClient.PostAsync(ollamaUrl, content);
            
            if (response.IsSuccessStatusCode)
            {
                string responseBody = await response.Content.ReadAsStringAsync();
                var ollamaResponse = JsonUtility.FromJson<OllamaResponse>(responseBody);
                return ollamaResponse.response;
            }
            else
            {
                return "Error querying Ollama: " + response.StatusCode;
            }
        }
        catch (System.Exception e)
        {
            return "Error: " + e.Message;
        }
    }

    [System.Serializable]
    public class OllamaRequest
    {
        public string model;
        public string prompt;
        public bool stream;
    }

    [System.Serializable]
    public class OllamaResponse
    {
        public string response;
        public string model;
        public int prompt_eval_count;
        public int eval_count;
    }

/////////////////////////////

        private void Update()
        {
            if (isRecording)
            {
                time += Time.deltaTime;
                progressBar.fillAmount = time / duration;
                
                if (time >= duration)
                {
                    time = 0;
                    isRecording = false;
                    EndRecording();
                }
            }
        }

        ////piper text-to-speech generation. Takes the response from Ollama and generates a wav file, which will be played in the audio source component
        private async System.Threading.Tasks.Task RunPiper(string text)
        {
            await System.Threading.Tasks.Task.Run(() =>
            {
                using (Process process = new Process())
                {
                    process.StartInfo.FileName = piperPath;
                    process.StartInfo.Arguments =
                        $"--model \"{piperModel}\" --output_file \"{piperOutput}\"";

                    process.StartInfo.RedirectStandardInput = true;
                    process.StartInfo.UseShellExecute = false;
                    process.StartInfo.CreateNoWindow = true;

                    process.Start();

                    process.StandardInput.Write(text);
                    process.StandardInput.Close();

                    process.WaitForExit();
                }
            });
        }
        //////////

        /// Coroutine to play the generated audio file from Piper
        private System.Collections.IEnumerator PlayGeneratedAudio()
        {
            string audioPath = piperOutput;

            while (!System.IO.File.Exists(audioPath))
            {
                yield return null;
            }

            using (UnityEngine.Networking.UnityWebRequest request =
                UnityEngine.Networking.UnityWebRequestMultimedia.GetAudioClip("file://" + audioPath, AudioType.WAV))
            {
                yield return request.SendWebRequest();

                if (audioSource.clip != null)
                {
                    Destroy(audioSource.clip);
                }

                AudioClip clip = UnityEngine.Networking.DownloadHandlerAudioClip.GetContent(request);
                audioSource.clip = clip;
                audioSource.Play();
            }
        }
        ///
        /// 
        void OnDestroy()
        {
            if (audioSource != null && audioSource.clip != null)
            {
                Destroy(audioSource.clip);
            }
        }
    }
}
